/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;



import java.awt.Color;

/**
 *
 * @author KJEFF
 */
public class Home extends javax.swing.JFrame {

    Color paneldefault;
    Color panelClick;
    
    public Home() {
        initComponents();
        
        paneldefault = new Color(42,39,41);
        panelClick = new Color(192,27,54);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pane1 = new javax.swing.JPanel();
        viewvendors = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pane2 = new javax.swing.JPanel();
        addcustomers = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pane9 = new javax.swing.JPanel();
        addgoods = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pane3 = new javax.swing.JPanel();
        viewgoods = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pane4 = new javax.swing.JPanel();
        issuedbills = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pane6 = new javax.swing.JPanel();
        addcategory = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pane8 = new javax.swing.JPanel();
        viewissuedgoods = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pane7 = new javax.swing.JPanel();
        toppanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(42, 39, 41));
        sidepanel.setAlignmentX(0.0F);
        sidepanel.setAlignmentY(0.0F);
        sidepanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        sidepanel.setMinimumSize(new java.awt.Dimension(200, 370));
        sidepanel.setPreferredSize(new java.awt.Dimension(200, 370));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(42, 39, 41));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 30));
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Home");
        home.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane1.setBackground(new java.awt.Color(42, 39, 41));
        pane1.setDoubleBuffered(false);
        pane1.setMaximumSize(new java.awt.Dimension(0, 0));
        pane1.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        home.add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        sidepanel.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 50));

        viewvendors.setBackground(new java.awt.Color(42, 39, 41));
        viewvendors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewvendorsMouseClicked(evt);
            }
        });
        viewvendors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewvendors.png"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel19.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel19.setPreferredSize(new java.awt.Dimension(30, 30));
        viewvendors.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("View Vendors");
        viewvendors.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane2.setBackground(new java.awt.Color(42, 39, 41));
        pane2.setDoubleBuffered(false);
        pane2.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        viewvendors.add(pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(viewvendors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        addcustomers.setBackground(new java.awt.Color(42, 39, 41));
        addcustomers.setMinimumSize(new java.awt.Dimension(118, 50));
        addcustomers.setPreferredSize(new java.awt.Dimension(118, 50));
        addcustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcustomersMouseClicked(evt);
            }
        });
        addcustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addgoods.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(30, 30));
        addcustomers.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Add Customers");
        addcustomers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane9.setBackground(new java.awt.Color(42, 39, 41));
        pane9.setDoubleBuffered(false);
        pane9.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane9Layout = new javax.swing.GroupLayout(pane9);
        pane9.setLayout(pane9Layout);
        pane9Layout.setHorizontalGroup(
            pane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane9Layout.setVerticalGroup(
            pane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        addcustomers.add(pane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(addcustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 50));

        addgoods.setBackground(new java.awt.Color(42, 39, 41));
        addgoods.setAlignmentX(0.0F);
        addgoods.setAlignmentY(0.0F);
        addgoods.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        addgoods.setMinimumSize(new java.awt.Dimension(118, 50));
        addgoods.setPreferredSize(new java.awt.Dimension(118, 50));
        addgoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addgoodsMouseClicked(evt);
            }
        });
        addgoods.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addgoods.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        addgoods.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Add Goods");
        addgoods.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane3.setBackground(new java.awt.Color(42, 39, 41));
        pane3.setDoubleBuffered(false);
        pane3.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane3Layout = new javax.swing.GroupLayout(pane3);
        pane3.setLayout(pane3Layout);
        pane3Layout.setHorizontalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane3Layout.setVerticalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        addgoods.add(pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(addgoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 50));

        viewgoods.setBackground(new java.awt.Color(42, 39, 41));
        viewgoods.setMinimumSize(new java.awt.Dimension(111, 50));
        viewgoods.setPreferredSize(new java.awt.Dimension(111, 50));
        viewgoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewgoodsMouseClicked(evt);
            }
        });
        viewgoods.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewgoods.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 30));
        viewgoods.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("View Goods");
        viewgoods.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane4.setBackground(new java.awt.Color(42, 39, 41));
        pane4.setDoubleBuffered(false);
        pane4.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane4Layout = new javax.swing.GroupLayout(pane4);
        pane4.setLayout(pane4Layout);
        pane4Layout.setHorizontalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane4Layout.setVerticalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        viewgoods.add(pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(viewgoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 50));

        issuedbills.setBackground(new java.awt.Color(42, 39, 41));
        issuedbills.setMinimumSize(new java.awt.Dimension(97, 50));
        issuedbills.setPreferredSize(new java.awt.Dimension(97, 50));
        issuedbills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuedbillsMouseClicked(evt);
            }
        });
        issuedbills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/issued.png"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel13.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel13.setPreferredSize(new java.awt.Dimension(30, 30));
        issuedbills.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Issued Goods");
        issuedbills.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane6.setBackground(new java.awt.Color(42, 39, 41));
        pane6.setDoubleBuffered(false);
        pane6.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane6Layout = new javax.swing.GroupLayout(pane6);
        pane6.setLayout(pane6Layout);
        pane6Layout.setHorizontalGroup(
            pane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane6Layout.setVerticalGroup(
            pane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        issuedbills.add(pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(issuedbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 50));

        addcategory.setBackground(new java.awt.Color(42, 39, 41));
        addcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcategoryMouseClicked(evt);
            }
        });
        addcategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/category.png"))); // NOI18N
        jLabel17.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 30));
        addcategory.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Add Category");
        addcategory.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane8.setBackground(new java.awt.Color(42, 39, 41));
        pane8.setDoubleBuffered(false);
        pane8.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane8Layout = new javax.swing.GroupLayout(pane8);
        pane8.setLayout(pane8Layout);
        pane8Layout.setHorizontalGroup(
            pane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane8Layout.setVerticalGroup(
            pane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        addcategory.add(pane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(addcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        viewissuedgoods.setBackground(new java.awt.Color(42, 39, 41));
        viewissuedgoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewissuedgoodsMouseClicked(evt);
            }
        });
        viewissuedgoods.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewissuedgoods.png"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel16.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel16.setPreferredSize(new java.awt.Dimension(30, 30));
        viewissuedgoods.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("View Issued Goods");
        viewissuedgoods.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        pane7.setBackground(new java.awt.Color(42, 39, 41));
        pane7.setDoubleBuffered(false);
        pane7.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pane7Layout = new javax.swing.GroupLayout(pane7);
        pane7.setLayout(pane7Layout);
        pane7Layout.setHorizontalGroup(
            pane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane7Layout.setVerticalGroup(
            pane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        viewissuedgoods.add(pane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidepanel.add(viewissuedgoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 200, 50));

        jPanel1.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 670));

        toppanel.setBackground(new java.awt.Color(192, 27, 54));
        toppanel.setAlignmentX(0.0F);
        toppanel.setAlignmentY(0.0F);
        toppanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toppanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        toppanel.setMinimumSize(new java.awt.Dimension(720, 115));
        toppanel.setPreferredSize(new java.awt.Dimension(720, 115));
        toppanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toppanelMouseDragged(evt);
            }
        });
        toppanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toppanelMousePressed(evt);
            }
        });
        toppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inventory Management System");
        toppanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/closing.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        toppanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        toppanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jPanel1.add(toppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 750, 70));

        jDesktopPane1.setAlignmentX(0.0F);
        jDesktopPane1.setAlignmentY(0.0F);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(740, 450));
        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("An inventory management system for a provision store that allows the store \nowner to add goods, view vendors, view goods, view bills, issued goods and view \nissued goods.\n\nItem Category\nHere are some of the categories that are useful in the store.\n1. Beverages – coffee/tea, juice, soda\n2. Bread/Bakery – sandwich loaves, dinner rolls, tortillas, bagels\n3. Canned/Jarred Goods – vegetables, spaghetti sauce, ketchup\n4. Dairy – cheeses, eggs, milk, yoghurt, butter\n5. Dry/Baking Goods – cereals, flour, sugar, pasta, mixes\n6. Frozen Foods – waffles, vegetables, individual meals, ice cream\n7. Meat – lunch meat, poultry, beef, pork\n8. Produce – fruits, vegetables\n9. Cleaners – all-purpose, laundry detergent, dishwashing liquid/detergent\n10.Paper Goods – paper towels, toilet paper, aluminium foil, sandwich bags\n11.Personal Care – shampoo, soap, hand soap, shaving cream");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel3);

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 750, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        Overview ov = new Overview();
        jDesktopPane1.add(ov).setVisible(true);
        
        //Show that, the clicked tab is active
        pane1.setBackground(panelClick);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_homeMouseClicked

    private void viewvendorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewvendorsMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        ViewVendors vv = new ViewVendors();
        jDesktopPane1.add(vv).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(panelClick);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_viewvendorsMouseClicked

    private void addgoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addgoodsMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        AddGoods ag = new AddGoods();
        jDesktopPane1.add(ag).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(panelClick);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_addgoodsMouseClicked

    private void viewgoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewgoodsMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        ViewGoods vg = new ViewGoods();
        jDesktopPane1.add(vg).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(panelClick);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_viewgoodsMouseClicked

    private void issuedbillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedbillsMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        IssuedGoods ig = new IssuedGoods();
        jDesktopPane1.add(ig).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(panelClick);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_issuedbillsMouseClicked

    private void viewissuedgoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewissuedgoodsMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        ViewIssuedGoods vig = new ViewIssuedGoods();
        jDesktopPane1.add(vig).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(panelClick);
        pane8.setBackground(paneldefault);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_viewissuedgoodsMouseClicked

    // when clicked it closes the frmae
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    // Allows to minimize the frame
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    // Frame can be moved
    int x, y;
    private void toppanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toppanelMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_toppanelMousePressed
    
    // allows to move the frame
    private void toppanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toppanelMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_toppanelMouseDragged

    private void addcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcategoryMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        Category cat = new Category();
        jDesktopPane1.add(cat).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(panelClick);
        pane9.setBackground(paneldefault);
    }//GEN-LAST:event_addcategoryMouseClicked

    private void addcustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustomersMouseClicked
        //Display screen
        jDesktopPane1.removeAll();
        Customer cust = new Customer();
        jDesktopPane1.add(cust).setVisible(true);
        
        //Shows that, the clicked tab is active
        pane1.setBackground(paneldefault);
        pane2.setBackground(paneldefault);
        pane3.setBackground(paneldefault);
        pane4.setBackground(paneldefault);
        pane6.setBackground(paneldefault);
        pane7.setBackground(paneldefault);
        pane8.setBackground(paneldefault);
        pane9.setBackground(panelClick);
    }//GEN-LAST:event_addcustomersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addcategory;
    public javax.swing.JPanel addcustomers;
    public javax.swing.JPanel addgoods;
    private javax.swing.JPanel home;
    private javax.swing.JPanel issuedbills;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JPanel pane3;
    private javax.swing.JPanel pane4;
    private javax.swing.JPanel pane6;
    private javax.swing.JPanel pane7;
    private javax.swing.JPanel pane8;
    private javax.swing.JPanel pane9;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel toppanel;
    private javax.swing.JPanel viewgoods;
    private javax.swing.JPanel viewissuedgoods;
    private javax.swing.JPanel viewvendors;
    // End of variables declaration//GEN-END:variables
}
