/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author KJEFF
 */
public class UpdateGoods extends javax.swing.JFrame {

    /**
     * Creates new form UpdateGoods
     */
    public UpdateGoods() {
        initComponents();
        GetCat();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtprodid = new javax.swing.JTextField();
        txtprodname = new javax.swing.JTextField();
        goodname = new javax.swing.JLabel();
        goodname1 = new javax.swing.JLabel();
        txtproddesc = new javax.swing.JTextField();
        quantity2 = new javax.swing.JLabel();
        quantity1 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        txtvendor = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        buyingprice = new javax.swing.JLabel();
        txtbuyingprice = new javax.swing.JTextField();
        txtcombocat = new javax.swing.JComboBox<>();
        category = new javax.swing.JLabel();
        updbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 39, 41));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/closing.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Goods");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        txtprodid.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        txtprodname.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        goodname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        goodname.setForeground(new java.awt.Color(42, 39, 41));
        goodname.setText("Product Name:");

        goodname1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        goodname1.setForeground(new java.awt.Color(42, 39, 41));
        goodname1.setText("Product Id:");

        txtproddesc.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        quantity2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        quantity2.setForeground(new java.awt.Color(42, 39, 41));
        quantity2.setText("Description:");

        quantity1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        quantity1.setForeground(new java.awt.Color(42, 39, 41));
        quantity1.setText("Quantity:");

        txtquantity.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        txtvendor.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        quantity.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(42, 39, 41));
        quantity.setText("Vendor:");

        buyingprice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        buyingprice.setForeground(new java.awt.Color(42, 39, 41));
        buyingprice.setText("Buying Price per/km:");

        txtbuyingprice.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        txtcombocat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        category.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        category.setForeground(new java.awt.Color(42, 39, 41));
        category.setText("Category:");

        updbtn.setBackground(new java.awt.Color(192, 27, 54));
        updbtn.setForeground(new java.awt.Color(255, 255, 255));
        updbtn.setText("Update");
        updbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(goodname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtprodid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(category)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcombocat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buyingprice)
                            .addComponent(quantity)
                            .addComponent(quantity1)
                            .addComponent(quantity2)
                            .addComponent(goodname))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtbuyingprice)
                                .addComponent(txtvendor)
                                .addComponent(txtquantity)
                                .addComponent(txtproddesc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtprodname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprodid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goodname1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprodname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goodname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcombocat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtproddesc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvendor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyingprice)
                    .addComponent(txtbuyingprice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // It sets combo box with data from the category table
    private void GetCat()
    {
        try
        {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/InventoryDB", "root", "root");
            St = Con.createStatement();
            String query = "select * from inventorydb.categorytb";
            Rs = St.executeQuery(query);
            while(Rs.next())
            {
                String MyCat = Rs.getString("catname");
                txtcombocat.addItem(MyCat);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    // Closes the frame
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
    
    // allows to move the frame or window
    int x, y;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    // allows to move the frame or window
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();        
    }//GEN-LAST:event_jPanel2MousePressed

    // declare variables to allow to connect, create and edit database
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    // Updates the product table in the database
    int grossprice;
    private void updbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updbtnMouseClicked
        grossprice = Integer.parseInt(txtquantity.getText()) * Integer.parseInt(txtbuyingprice.getText());
        if(txtprodid.getText().isEmpty() || txtprodname.getText().isEmpty() || txtproddesc.getText().isEmpty() || txtquantity.getText().isEmpty() || txtvendor.getText().isEmpty() || txtbuyingprice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Missing Information!");
        }
        else
        {
            try
            {
                String txtGrossPrice = Integer.toString(grossprice);
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/InventoryDB", "root", "root");
                String UpdateQuery = "update inventorydb.producttb set prodname='"+txtprodname.getText()+"'"+", prodcat='"+txtcombocat.getSelectedItem().toString()+"'"+", proddesc='"+txtproddesc.getText()+"'"+", prodqty="+txtquantity.getText()+""+", prodvend='"+txtvendor.getText()+"'"+", prodbuyp="+txtbuyingprice.getText()+""+", prodgrossp="+txtGrossPrice+""+" where prodid="+txtprodid.getText();
                Statement Add = Con.createStatement();
                Add.executeUpdate(UpdateQuery);
                this.dispose();
                Con.close();
            }catch(SQLException e)
            {
                e.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_updbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateGoods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buyingprice;
    private javax.swing.JLabel category;
    private javax.swing.JLabel goodname;
    private javax.swing.JLabel goodname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel quantity1;
    private javax.swing.JLabel quantity2;
    public javax.swing.JTextField txtbuyingprice;
    public javax.swing.JComboBox<String> txtcombocat;
    public javax.swing.JTextField txtproddesc;
    public javax.swing.JTextField txtprodid;
    public javax.swing.JTextField txtprodname;
    public javax.swing.JTextField txtquantity;
    public javax.swing.JTextField txtvendor;
    private javax.swing.JButton updbtn;
    // End of variables declaration//GEN-END:variables
}
